spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notifier_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8080}
logging:
  level:
    root: INFO
